### ISSUE TITLE
Signing in after trying to open a specific testing ground takes me to the welcome page

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etloader#104]
I tried opening http://ivy.et-engine.com/testing_grounds/45 without being signed in to Ivy and got (as expected) the warning below. When I signed in I was taken to http://ivy.et-engine.com/welcome and not to the specific testing ground (#45), as I was expecting.

![screen shot 2015-05-12 at 16 15 43](https://cloud.githubusercontent.com/assets/4669028/7589314/2deb24d0-f8c2-11e4-912a-6f29259ffcf5.png)

@grdw, this is a very minor issue, but I think it is nicer if you go straight to the specific testing ground after signing in without having to retype the URL.

**Comment by grdw** [comment]
Fixed with e43e9be
