### ISSUE TITLE
The debug window does not show an image (on my machine)

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#11]
![ivy](https://cloud.githubusercontent.com/assets/1303760/5921059/5a887e76-a641-11e4-8b28-75727993076d.png)

Just a stab in the dark: is this an ImageMagick problem?

**Comment by antw** [comment]
Closing since since is solved with the new calculator.

ImageMagick is the likely culprit; I think maybe it hasn't been installed on your new laptop? `brew install imagemagick` will solve that, but isn't necessary unless you plan on debugging Refinery graphs.
