### ISSUE TITLE
It is not possible to add storage and conversion technologies to a testing ground

### ISSUE THREAD

**Issue by jorisberkhout** [quintel/etloader#112]
I tried adding a battery by specifying `households_flexibility_p2p_electricity` as technology type http://ivy.et-engine.com/testing_grounds/54 but got the error message shown below. Adding a `energy_flexibility_p2g_electricity` (P2G) or `households_flexibility_p2h_electricity` (P2H) fails in a similar fashion.

![screen shot 2015-05-13 at 12 28 42](https://cloud.githubusercontent.com/assets/4669028/7609149/418d65ee-f970-11e4-9eb7-cc33d88d9df0.png)

**Comment by antw** [comment]
Closing, as this is now working correctly.
