### ISSUE TITLE
'Bug' in testing ground#new profile table

### ISSUE THREAD

**Issue by grdw** [quintel/etloader#117]
When you remove a node completly from the table and change between concurrencies, it 'spawns' back the old node.

**Comment by grdw** [comment]
@ChaelKruip considering that I can't change the topology endpoints from the table, but can remove all technologies under a certain endpoint - how should 'automatic concurrency' be handled in this case?

I'll show you what's happening if the above isn't clear enough (considering that I'd some issues trying to put the above words in the proper order)

**Comment by ChaelKruip** [comment]
As discussed with @grdw, the division of technologies over the nodes needs to be disconnected from the 'concurrency'.

If the user removes all technologies from an end-point, that end-point should remain empty. @grdw will pick this up after the deadline.

**Comment by grdw** [comment]
Continued at #137
