### ISSUE TITLE
Do we assume that the battery of EV is empty upon return?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#120]
Or can it still contain some residual charge IF the battery was charged beyond the prescribed charging fraction (due to excess local electricity from solar PV).

**Comment by antw** [comment]
Is this meant as a question, or to start a discussion? It was [briefly discussed here](https://github.com/quintel/etloader/issues/66#issuecomment-99513177) with the decision being to empty the EV completely upon its return.

I think it would be more accurate for it to return with the excess still intact.

**Comment by ChaelKruip** [comment]
> I think it would be more accurate for it to return with the excess still intact.

I agree. That would be a nice-to-have IMO.

**Comment by ChaelKruip** [comment]
> Is this meant as a question, or to start a discussion?

I was wondering what was currently implemented :)

**Comment by ChaelKruip** [comment]
Superseded by https://github.com/quintel/etloader/issues/131. Closing.
