### ISSUE TITLE
On the "load chart page", use the table view for technologies connected to a node

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#126]
Right now this is the representation of connected technologies:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7640053/1a204af0-fa81-11e4-8069-305df28b085c.png)

The table view is much more economical and pretty :smile: 

Perhaps we could even allow it to be editable? @dennisschoenmakers @antw what do you think?

**Comment by dennisschoenmakers** [comment]
>  @dennisschoenmakers @antw what do you think?

Why not? :smiley:

**Comment by ChaelKruip** [comment]
> Why not? :smiley:

Because editing it would trigger a re-calculation of the load. Currently this page is nice and responsive because information is largely cached if I'm not mistaken. @antw?

**Comment by antw** [comment]
> Currently this page is nice and responsive because information is largely cached if I'm not mistaken. @antw?

There is currently no caching of calculated testing grounds. We would, of course, have to recalculate the testing ground after a change is made, but that's also true of using the "Edit testing ground" page.

Seems like this could be a nice usability improvement.

**Comment by grdw** [comment]
And there is a table:

![screen shot 2015-05-18 at 10 37 37 am](https://cloud.githubusercontent.com/assets/2676542/7677139/f2533cbe-fd49-11e4-8765-772f56835187.png)

**Comment by ChaelKruip** [comment]
:+1:
