### ISSUE TITLE
Ivy has trouble loading a topology for my medium sized (~100) connections testing ground

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#13]
The testing ground defined in [this gist](https://gist.github.com/ChaelKruip/75669f0b63ab40bca0d4) does not result in a network graph showing up...

The interface shows "topology loading" for a long time and then stops.

**Comment by antw** [comment]
Should be fixed now.

However, [the technology list](https://gist.github.com/ChaelKruip/75669f0b63ab40bca0d4#file-technologies-yml) in that Gist has duplicate keys (for example, `HH #3` appears four times). When the YAML library parses the file, it will discard all but the last occurrence of a key, meaning some of your technologies are not getting saved.
