### ISSUE TITLE
http://ivy.et-engine.com/testing_grounds/import is broken

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#132]
I don't know how but I might have broken it by defining a new topology :worried:

**Comment by antw** [comment]
Did you rename the default topology? It used to be defined in a YAML file, but has apparently been moved into the database and [*must* be called "Default topology"](https://github.com/quintel/etloader/blob/master/app/models/topology.rb#L9-L11).

**Comment by ChaelKruip** [comment]
That's probably what happened yes... I'll fix it tomorrow. Thanks!

**Comment by ChaelKruip** [comment]
Fixed. Closing.
