### ISSUE TITLE
Suggestions for improving the "testing_grounds/new" page

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#29]
Perhaps the windows could be positioned side-by-side and have a title something like:
![ivy_page_key](https://cloud.githubusercontent.com/assets/1303760/6614716/49930aea-c89d-11e4-86b8-576a13b0bc7f.png)

**Comment by ChaelKruip** [comment]
Re-assigning to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by dennisschoenmakers** [comment]
Actually, I think we need to have a 'clearer' show page: then these 'two things' will be separated. Closing.
