### ISSUE TITLE
NICE TO HAVE: When editing a testing ground the topology YAML shows extra characters

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#30]
![ivy](https://cloud.githubusercontent.com/assets/1303760/6614889/242ea7bc-c89f-11e4-9975-41648de7592b.png)

It works fine but looks ugly :)

**Comment by ChaelKruip** [comment]
This only seems to happen if you try to create the testing ground after an edit and there is an error that prevents the testing ground from being computed (like specifying both a profile and a load).

**Comment by ChaelKruip** [comment]
Assigned @grdw

**Comment by antw** [comment]
I already fixed this locally, so I'll assign to me to avoid duplicating work.
