### ISSUE TITLE
When editing a testing ground, it would be nice to be able to upload a CSV

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#34]
![ivy](https://cloud.githubusercontent.com/assets/1303760/6615134/6c9bda9a-c8a1-11e4-87be-b3a687587ce7.png)

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
Waiting for #88 to be merged before I continue with this.

**Comment by grdw** [comment]
@ChaelKruip is this still needed?

**Comment by ChaelKruip** [comment]
Yes please!

**Comment by ChaelKruip** [comment]
The download/upload a CSV functionality allows the user to quickly build/reuse complex LESs.
