### ISSUE TITLE
Some 'navigation' for the different 'topics' of ETLoader is needed

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#35]
When looking at a testing ground, the user should be able to navigate to the 'load profiles' section and vice versa. This will become more relevant if we also support more testing-ground functionality such as 'business cases' and 'market models'.

Perhaps we could make different tabs for the different 'topics'?

**Comment by ChaelKruip** [comment]
Re-assigning to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by dennisschoenmakers** [comment]
See #48.
