### ISSUE TITLE
Load profile charts need a bit of improving

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#37]
![ivy](https://cloud.githubusercontent.com/assets/1303760/6616307/fcf2715c-c8ac-11e4-946c-ab8c29a606e7.png)

* ~~Small numbers are all displayed as 0.00.~~ Perhaps we could use scientific notation here?
* ~~The axes need labeling~~
* ~~The chart needs to show (without the need to refresh the page)~~
* The chart needs to show all points (the last 24 hours seems to be missing)

**Comment by ChaelKruip** [comment]
Related to https://github.com/quintel/etloader/issues/24 https://github.com/quintel/etloader/issues/25

**Comment by ChaelKruip** [comment]
Re-assigning to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by dennisschoenmakers** [comment]
Re-assigning @antw since this contains diving into D3.

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
> The axes need labeling

![screen shot 2015-05-04 at 2 49 15 pm](https://cloud.githubusercontent.com/assets/2676542/7453745/d79162da-f26c-11e4-814c-0e0aabfa9876.png)

**Comment by grdw** [comment]
Perhaps we could use scientific notation here? -> #91
