### ISSUE TITLE
Proposal: testing ground navigation

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#40]
This is a working document for the design of an interface that accommodates the newly developed functionality for testing ground calculations.

After talking to @AlexanderWirtz I feel that one intuitive option would be to use a side-bar menu similar to that of the (professional) ETM:
![ivy_page_key](https://cloud.githubusercontent.com/assets/1303760/6671038/d350807e-cc02-11e4-8e70-f3bb896b5369.png)

There are several advantages to this:

* A certain amount of 'homogeneity' with the ETM
* Familiarity with how such a menu works (if the user is familiar with the ETM)
* Re-usability of design and framework

**Comment by ChaelKruip** [comment]
@jorisberkhout @AlexanderWirtz @dennisschoenmakers please chip in!

**Comment by ChaelKruip** [comment]
And @antw of course as well! :smile:

**Comment by antw** [comment]
The main navigation will go at the top, if possible. Most people don't have 27" monitors, and even those that do don't typically fill the entire monitor with their browser. At-the-top will leave more space for the main content.

This is a usability problem with the current ETM design, although I'm lacking a better alternative as the ETM has too many items to be changed back to a top-menu (also, the dashboard and sponsor logos also constrain us vertically). I'd rather not blindly do as the ETM does just for the sake of familiarity.

> Re-usability of design and framework

I don't plan on reusing any code from ETModel if I can help it. :grimacing:

**Comment by ChaelKruip** [comment]
> At-the-top will leave more space for the main content.

Good point.

> I don't plan on reusing any code from ETModel if I can help it.

I trust your judgement there @antw

**Comment by ChaelKruip** [comment]
Another idea (credit goes to @grdw) is to use 'bread crumbs' to navigate the user through the various stages of creating and analysing a testing ground. I imagine this could look something like this:
![ivy_page_key](https://cloud.githubusercontent.com/assets/1303760/6755349/bfbccf86-cf22-11e4-8a56-2c1512734dcd.png)

This is a very crude sketch but here is what I see as advantages:
* There is a clear order in which the user can build the testing ground
* We can use different colours to signify if a 'stage' of the process has yet been completed 
  * filled crumbs have already been visited and are available to jump (back) to
  * 'open' (non-filled) crumbs are not yet available
  * the 'active' crumb is not greyed-out (the rest is)

@antw let me know what yo think!

**Comment by ChaelKruip** [comment]
Re-assigned to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by dennisschoenmakers** [comment]
See PR #48
