### ISSUE TITLE
Load profiles seem to have been 'scaled' wrongly at some point

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#41]
I know this is a vague title but I'll try to explain :wink: 

When the first 92 datapoints of the base-load profile for HH# 1 in the Lochem testing ground are downloaded and plotted (in Excel) you see quite a bit of variation:
![hh__1_csv](https://cloud.githubusercontent.com/assets/1303760/6729596/290e102a-ce34-11e4-8508-233660a40da8.png)

Displaying the load-profile in the "Ivy" shows are very different picture:
![ivy](https://cloud.githubusercontent.com/assets/1303760/6730598/75c08704-ce3e-11e4-9a0d-ba98e17960f1.png)

This is puzzling!

**Comment by antw** [comment]
This and #24 are basically the same issue: the front-end chart does not display every point in the curve. In the front-end, the curve is down-sampled to 356 points (one-per-day) for performance reasons.

We need a [HighStock-like solution](http://www.coindesk.com/price/) whereby zooming in displays higher resolution data (since one-point-per-day makes no sense when you are so far zoomed in).

**Comment by ChaelKruip** [comment]
Thanks @antw for pointing this out. I have some suggestions ranging from easy to possibly very difficult to improve the charts:

* Instead of averaging per day, we could plot 2 points per day, one with the maximum and one with the minimum of that day. That would allow the user to appreciate the extremes in the data (which are the most important anyway).
* We could have a toggle between showing the current chart (all year, one day resolution) and a similar chart showing a week with hour/15 minute resolution. The user should be able to select the week in some way for this option.
* We could allow the user to specify time-window and plotting resolution before clicking a 'draw' button.
* We could try to implement a 'HighStock-like' zooming functionality :stuck_out_tongue:

**Comment by antw** [comment]
> * Instead of averaging per day, we could plot 2 points per day, one with the maximum and one with the minimum of that day. That would allow the user to appreciate the extremes in the data (which are the most important anyway).

A good, sensible suggestion. But it doesn't really work out. :disappointed:

![sawtooth](https://cloud.githubusercontent.com/assets/4383/6734712/a690abee-ce51-11e4-8330-a0f538fb1dd2.jpg)

730 points is getting close to having more data points than there are pixels on the page to show them; the result is the above, somewhat ugly chart. Also, when down-sampling, we're choosing the *maximum* value from each 12-hour period, so the full extremes cannot be appreciated.

That problem can be solved of course, but increasing to 730 points isn't the only step required to fix this.

> * We could have a toggle between showing the current chart (all year, one day resolution) and a similar chart showing a week with hour/15 minute resolution. The user should be able to select the week in some way for this option.
> * We could allow the user to specify time-window and plotting resolution before clicking a 'draw' button.

These are also smart solutions which won't take too long to implement. I don't think either is ideal – they'll feel a bit "clunky" and awkward – but I guess either would be an improvement on what we have presently.

> * We could try to implement a 'HighStock-like' zooming functionality :stuck_out_tongue:

This is what I want to do, *time-permitting*, as it'll be a great excuse to learn more about d3.js, but I think it will cost us a lot of time.

Option 3 for now, option 4 later?

*FWIW: I always considered the current chart to be a stopgap, and was going to add Google finance / Highstock zooming at some stage.*

**Comment by ChaelKruip** [comment]
> Option 3 for now, option 4 later?

I agree with everything you have said here @antw. I would indeed draw the current as a default for the time being and allow the user to re-draw with specified window and resolution. However much I would like the 'zooming' I think for the moment it is not worth the time investment.

**Comment by ChaelKruip** [comment]
One more idea about the load charts:

Maybe we could plot both the maximum values per day and the minimum values per day but **as two distinct curves** (each with resolution of 24 hours). In this way, we show the 'envelope' of the profiles without all the 'jiggles' in between that make the charts hard to read.

**Comment by ChaelKruip** [comment]
Re-assigning to @dennisschoenmakers so he can shine his light on this and find someone to make this happen.

**Comment by dennisschoenmakers** [comment]
Assigned back to @antw as discussed with @ChaelKruip

**Comment by ChaelKruip** [comment]
Closing as this issue does not describe the current situation accurately anymore.
