### ISSUE TITLE
Demand and capacity of solar panels does not seem to be correctly communicated to testing ground

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#43]
For the same scenario as in https://github.com/quintel/etloader/issues/42, the capacities and demands of all solar panels are zero. I could expect them to be non-zero: the capacities something like 1.5 (kW) and the demand to be a negative number that would give the yearly production of solar PV (kWh).

![ivy](https://cloud.githubusercontent.com/assets/1303760/6776961/41c09188-d145-11e4-866a-0874f7b71b66.png)

**Comment by antw** [comment]
Fixed by deploying the latest ETEngine beta. Note that the gas technologies won't have a load, because they lack an `electricity_input_capacity`; we're going to need an equivalent attribute for them.

**Comment by ChaelKruip** [comment]
> Note that the gas technologies won't have a load,

That's fine. We don't want to model them explicitly so they can be removed (as the coal heater).
