### ISSUE TITLE
Technologies which should be modeled explicitly in testing ground scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#44]
For the ETM technologies listed below, the testing ground scenario should include:

* **capacity** [kW]: given by the 'electricity_output_capacity' (for producing technologies) and 'input_capacity' (for consuming technologies)
* **demand** [kWh]: given by multiplying the demand of ETE [MJ] by 0.27777777.... Positive for consuming technologies and negative for producers
* **number_of_units**: unnecessary for testing grounds where every connection to the network represents a single household but very useful if a connection were to represent a bunch of households (as for larger testing grounds).

The technologies that are relevant:

* households_solar_pv_solar_radiation (producer)
* households_water_heater_heatpump_air_water_electricity (consumer)
* households_water_heater_heatpump_ground_water_electricity (consumer)
* households_space_heater_heatpump_air_water_electricity (consumer)
* households_space_heater_heatpump_ground_water_electricity (consumer)
* transport_car_using_electricity (consumer)

To the above technologies, load-profiles should be assigned and scaled by the capacity of the technology.

**Comment by antw** [comment]
> The technologies that are relevant: [...]

Are those the *only* technologies we want (for now), or *in addition* to [what we currently have](https://github.com/quintel/etloader/tree/master/data/technologies)?

**Comment by ChaelKruip** [comment]
> Are those the only technologies we want (for now), or in addition to what we currently have?

I think these are the only ones (for now). The wind_turbines would be nice to keep though but the combi-boiler and coal-thing can definitely go.
