### ISSUE TITLE
Perhaps we could show a list of saved scenario's instead of a place to put an ID?

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#51]
![ivy](https://cloud.githubusercontent.com/assets/1303760/6867813/07ffb7d2-d486-11e4-9647-e64fabdf5c2b.png)

**Comment by ChaelKruip** [comment]
Assigning @grdw

**Comment by grdw** [comment]
How would I filter the scenario's from et-engine, considering that some scenario's contain 'private' information?

**Comment by grdw** [comment]
Continued at #95 - closing this one.
