### ISSUE TITLE
Website should be protected by a password

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etloader#57]
I think the best way is to add a simple `User` model and start with a simple 'one general user' that everybody can use for the time being. Later we can add `users` to `testing_grounds` and implement authorization schemes.

**Comment by ChaelKruip** [comment]
:+1:

**Comment by ChaelKruip** [comment]
Assigning to @grdw to pick up at the end of this month.

**Comment by grdw** [comment]
Fixed with f9e1560...df86ecb

Still needs to be merged though.

Also does every page needs to behind a login wall?

**Comment by ChaelKruip** [comment]
> Also does every page needs to be behind a login wall?

As discussed with @grdw: for now we put everything behind a login. Closing.
