### ISSUE TITLE
Solar panels should have negative load

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#63]
We could give them a negative capacity? Or make the load profile negative?

@dennisschoenmakers @antw what do you think?

**Comment by ChaelKruip** [comment]
Perhaps the most elegant solution would be to add a check-box (or something like that) in the profiles interface that let's you chose between "consumption" and "production" profiles.

If a profile is of the "production" type, the profile is multiplied by -1.

**Comment by antw** [comment]
> We could give them a negative capacity? Or make the load profile negative?

Either should work, but I think giving a negative `capacity` is more consistent with what we show in the topology diagram. Users may otherwise be confused why their technology, with a greater than zero `capacity`, is "magically" showing a load of less than zero.

**Comment by ChaelKruip** [comment]
> Users may otherwise be confused why their technology, with a greater than zero capacity, is "magically" showing a load of less than zero.

I agree that this could be confusing. On the other hand, users think of their solar panels as having a certain (positive) capacity. It could be confusing if the user is required to put a minus sign before the capacity of solar panels. But I like the fact that it is explicitly clear that producers differ from consumers. 

> Either should work, but I think giving a negative capacity is more consistent with what we show in the topology diagram. 

Let's do it! :smile:

**Comment by ChaelKruip** [comment]
@antw is this difficult to do? If not could you give it priority? Thanks!

**Comment by ChaelKruip** [comment]
:+1:
