### ISSUE TITLE
Allow the user to create a scaled scenario from 'current' scenario

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#69]
When you click "create testing ground" you end up here:
![energy_transition_model_-_your_free__independent__comprehensive__fact-based_scenario_builder_](https://cloud.githubusercontent.com/assets/1303760/7134531/fe3d2632-e29d-11e4-98ab-8566f0017377.png)

It would be more convenient to use the 'current' scenario instead of a 'new'. The 'new' options is redundant since we have the button in the ETM.

**Comment by grdw** [comment]
Isn't this issue solved by #70 ?

**Comment by ChaelKruip** [comment]
> Isn't this issue solved by #70 ?

Yes. Closing.
