### ISSUE TITLE
The work-flow for creating testing grounds should become more intuitive

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#70]
There is very little 'persistence' when going from ETM to the ['scaling interface'](http://beta.pro.et-model.com/scaled) and, subsequently to [the testing ground environment](http://ivy.et-engine.com).

The user should be 'guided' through the steps more and get a better idea about the work-flow of creating, analysing en merging testing grounds.

**Comment by ChaelKruip** [comment]
Earlier comments by @dennisschoenmakers:

To consider:
- [ ] What if this is an already scaled scenario?
- [ ] Can we do this for all Areas?
- [ ] The flow is not logical now: you still have to save the scenario first. Could we add an option to the select list of the **Current* scenario?

**Comment by grdw** [comment]
- Save and go to testing ground env 'button' as replacement for 'creating testing ground' menu link.
- Set scenario name: "Nationale scenario + <scaled to size> + <numbering>"
- List scenarios from user
- Single sign in

**Comment by dennisschoenmakers** [comment]
> Single sign in accross multiple application with CAS? (or if anyone has another technological idea, please do tell - https://github.com/rubycas/rubycas-client / https://github.com/rubycas/rubycas-server). This is quite a 'huge' step though.

How huge exactly? How much time would it take to implement it across etmodel, etengine and etloader?

**Comment by grdw** [comment]
It would take the following things: 

- A CAS server to function as an authenticator. At this server the user would sign in (i.e. the sign-in POST call doesn't go to 'sign_in_path' but to the CAS server). 
- All the applications (etmodel, etengine, etloader) have to be registered as CAS-clients. 

*Unknowns:*
- I have to investigate in how well - I'd guess the current devise-authentication - will integrate with CAS.  There might be a case where it doesn't and devise needs to be replaced (this would take up a lot of time ) (https://github.com/nbudin/devise_cas_authenticatable just found this though, might make things easier). 

I'm thinking - and this is a rough 'wet-finger-pointing-in-the-sky'-type of estimate - it would take 2 to 3 weeks in order to get this working properly.

**Comment by ChaelKruip** [comment]
> it would take 2 to 3 weeks in order to get this working properly.

As discussed with @grdw and @dennisschoenmakers, the most important thing right now is to communicate the scenario ID from ETModel to ETLoader. We will look into fancier approaches later.

**Comment by grdw** [comment]
> - Save and go to testing ground environment-'link' as replacement for 'creating testing ground' menu link.
> - Set scenario name: "Nationale scenario + [scaled to size] + [numbering]"

These two are fixed

> - List scenarios from user

This depends on #57

**Comment by grdw** [comment]
The only thing that's missing is the parent 'url'. There are multiple ways to save the parent id in `etloader`.

The simplest one - is doing an API call to etengine and asking for the current scenario.

Another way is passing the parent id from et-engine, in et-modal to et-loader (which sounds as complicated as it is).

**Comment by ChaelKruip** [comment]
> The simplest one - is doing an API call to etengine and asking for the current scenario.

Let's do that one then! :smile:

**Comment by dennisschoenmakers** [comment]
With 'current' you mean 'latest', right? Might this not lead to
confusion when a scenario has just been created by another user or
application?

**Comment by grdw** [comment]
I don't mean latest, I mean the parent scenario from the `scenario_id` that's stored with a `testing_ground`.

**Comment by dennisschoenmakers** [comment]
:+1:

**Comment by grdw** [comment]
Fixed the parent scenario id issue with 97a3fda

Also added separators between the 'national scenario' and 'scaled scenario' links, as discussed with @ChaelKruip 

Also setted a max-height for the topology; which is now 500px. https://github.com/quintel/etloader/blob/cc3e3861fc2eb2a0b5b49fdf913ed4061e596295/app/assets/javascripts/showTree.js#L34

**Comment by ChaelKruip** [comment]
Closing this lengthy ticket. See https://github.com/quintel/etloader/issues/79 for the jest.
