### ISSUE TITLE
Number formatting of the load chart needs some improvement

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#78]
Large numbers 'fall off the side':
![ivy](https://cloud.githubusercontent.com/assets/1303760/7270805/0ae4950e-e8df-11e4-9305-5dc6b2834cb8.png)

Small numbers are all displayed as 0.0:
![ivy](https://cloud.githubusercontent.com/assets/1303760/7270930/1d9ec650-e8e0-11e4-9c0b-0d1fe5b66f8d.png)

**Comment by grdw** [comment]
Fixed this - still need someone to look into it.
Will be deployed when validated.
