### ISSUE TITLE
Load profile; use scientific notation in the graph for small number.

### ISSUE THREAD

**Issue by grdw** [quintel/etloader#91]
Small numbers in load profiles: use scientific notation here?

**Comment by ChaelKruip** [comment]
> Small numbesr in load profiles: use scientific notation here?

If possible, I'd like scientific notation for small numbers

**Comment by antw** [comment]
Scientific notation may be a bit technical for some users; perhaps we could change the unit from kW to MW to GW as appropriate?

The [Quantity class](https://github.com/quintel/etmodel/blob/master/app/assets/javascripts/lib/models/quantity.coffee) in ETModel does this quite nicely, but we'd have to pull in [i18n-js](https://rubygems.org/gems/i18n-js) to use it.

**Comment by ChaelKruip** [comment]
> Scientific notation may be a bit technical for some users; perhaps we could change the unit from kW to MW to GW as appropriate? Or from kW to W for smaller numbers.

I like that solution @antw!

**Comment by ChaelKruip** [comment]
Closing as this is issue is superseded by https://github.com/quintel/etloader/issues/139
