### ISSUE TITLE
When you make a mistake for a new TestingGround, the Hashes becomes a HashWithIndifferentAccess

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etloader#92]
![image](https://cloud.githubusercontent.com/assets/104830/7512612/8727f5fe-f4ae-11e4-8067-49f5d07d4bca.png)

**Comment by antw** [comment]
Duplicate of #30. :wink:

**Comment by dennisschoenmakers** [comment]
> Duplicate of #30. :wink:

:blush:
