### ISSUE TITLE
I am not Chael Kruip

### ISSUE THREAD

**Issue by dennisschoenmakers** [quintel/etloader#93]
When I create a TestingGround, it says I am Chael Kruip, logged in a dennis@quintel.com

![image](https://cloud.githubusercontent.com/assets/104830/7512697/fb3f7ebc-f4ae-11e4-969d-5f36aba177f7.png)

@antw: or is this a duplicate again? :smile:

**Comment by ChaelKruip** [comment]
> I am not Chael Kruip

How is that an issue?!

**Comment by antw** [comment]
> How is that an issue?!

Jealousy is a very real problem.

**Comment by ChaelKruip** [comment]
:laughing:

**Comment by grdw** [comment]
I fixed this issue https://github.com/quintel/etloader/commit/aa9cf81670cf36c77b6f8b41a13c78e7aacacb3c 

All the testing grounds are still connected to Chael though :angel:
