### ISSUE TITLE
Collapsing the 'steps' would make the workflow more intuitive

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/etloader#96]
It would be nice if steps 2 through 4 would be 'folded' when arriving:

![ivy](https://cloud.githubusercontent.com/assets/1303760/7513299/6ba875e2-f4b3-11e4-826e-d16bb90bd5f2.png)

**Comment by grdw** [comment]
I did some really quick and dirty out-of-the-box bootstrap 'hacking' to give you an impression of my idea:

![screen shot 2015-05-07 at 1 47 47 pm](https://cloud.githubusercontent.com/assets/2676542/7514663/c1067e56-f4bf-11e4-8411-d4c14d881962.png)

Together with #95 this becomes a lot easier to use.

**Comment by ChaelKruip** [comment]
:+1: Already a big improvement IMO! @dennisschoenmakers @antw what do you think?

**Comment by ChaelKruip** [comment]
@dennisschoenmakers, @grdw and I decided to collaps them even further into a single HTML table. Closing this issue as it is outdated.
